[package]
name = "git-branch-prune"
version = "0.1.0"
authors = ["Benoît Rocco <benoit.rocco@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
